/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ChatRegistryInterface extends Interface {
    getFunction(nameOrSignature: "encryptionKeys" | "getEncryptionKey" | "registerIdentity" | "sendMessage"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "IdentityRegistered" | "MessageSent"): EventFragment;

    encodeFunctionData(functionFragment: 'encryptionKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEncryptionKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerIdentity', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'sendMessage', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'encryptionKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEncryptionKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendMessage', data: BytesLike): Result;
  }

  
    export namespace IdentityRegisteredEvent {
      export type InputTuple = [user: AddressLike, encryptionKey: BytesLike];
      export type OutputTuple = [user: string, encryptionKey: string];
      export interface OutputObject {user: string, encryptionKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MessageSentEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, messageHash: BytesLike, tipAmount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [from: string, to: string, messageHash: string, tipAmount: bigint, timestamp: bigint];
      export interface OutputObject {from: string, to: string, messageHash: string, tipAmount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ChatRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ChatRegistry;
    waitForDeployment(): Promise<this>;

    interface: ChatRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    encryptionKeys: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    getEncryptionKey: TypedContractMethod<
      [_user: AddressLike, ],
      [string],
      'view'
    >
    

    
    registerIdentity: TypedContractMethod<
      [_encryptionKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    sendMessage: TypedContractMethod<
      [_to: AddressLike, _messageHash: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'encryptionKeys'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getEncryptionKey'): TypedContractMethod<
      [_user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerIdentity'): TypedContractMethod<
      [_encryptionKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sendMessage'): TypedContractMethod<
      [_to: AddressLike, _messageHash: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'IdentityRegistered'): TypedContractEvent<IdentityRegisteredEvent.InputTuple, IdentityRegisteredEvent.OutputTuple, IdentityRegisteredEvent.OutputObject>;
getEvent(key: 'MessageSent'): TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;

    filters: {
      
      'IdentityRegistered(address,bytes)': TypedContractEvent<IdentityRegisteredEvent.InputTuple, IdentityRegisteredEvent.OutputTuple, IdentityRegisteredEvent.OutputObject>;
      IdentityRegistered: TypedContractEvent<IdentityRegisteredEvent.InputTuple, IdentityRegisteredEvent.OutputTuple, IdentityRegisteredEvent.OutputObject>;
    

      'MessageSent(address,address,bytes32,uint256,uint256)': TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
      MessageSent: TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
    
    };
  }