/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChatRegistry } from "./ChatRegistry";
export * as factories from "./factories";
export { ChatRegistry__factory } from "./factories/ChatRegistry__factory";
